### ISSUE TITLE
doesn't work on Kotlin version 1.1.61

### ISSUE THREAD

**Issue by zhengyi5403** [zweifisch/ob-kotlin#2]
GNU Emacs 25.3.1
Kotlin version 1.1.61

**Comment by mardukbp** [comment]
It works with Kotlin 1.2.61 and Emacs 24.5.1 under Ubuntu 16.04. Did you try running kotlin in eshell?

**Comment by zweifisch** [comment]
kotlin syntax changed, the examples were outdated
